### ISSUE TITLE
Missing bits

### ISSUE THREAD

**Issue by Pcummings** [evalphobia/go-logdna#2]
Hi Here,

FYI your code is not logging app and env, I updated the code to do so, but can't create a pull request...

```
func (c *Client) Emit(line string, opt ...map[string]interface{}) error {
	d := LogData{
		Message: line,
		App:     c.App,
		Env:     c.Env,
	}
	if len(opt) != 0 {
		d.Meta = opt[0]
	}

	return c.emit(d)
}
```

**Comment by benrolfe** [comment]
@evalphobia I have the same issue with the `App` and `Env` missing, could you possibly resolve?

**Comment by evalphobia** [comment]
@Pcummings Thank you for suggesting fixing 🍰 
@benrolfe Thank you for pinging me 🥥 

(my LogDNA account had something wrong and could not write log... maybe It's inactive too old so I recreated the account.)

I've changed the codes and confirm sending logs. (and tag to v0.2.0)
https://github.com/evalphobia/go-logdna/releases/tag/v0.2.0

Would you guys confirm the fixing and close this issue?

**Comment by benrolfe** [comment]
@evalphobia Thanks, that's working now. Thanks for the quick fix.
